In [1]:
from warnings import filterwarnings
filterwarnings("ignore")

In [2]:
import pandas as pd
import numpy as np
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import QuantileTransformer
from sklearn.linear_model import LogisticRegression
np.random.seed(2017)

In [3]:
FEATURES = ['score' + str(x+1) for x in range(6)]
FEATURES.remove('score1')
TARGET = ['target']

In [4]:
train = pd.read_csv('../../data/combined/data.csv')
train = train[train['source'] == 'ISIC20']
train = train[['image_id','fold','target']]
score1 = pd.read_csv('../../score/metadata_train_score.csv')[['image_name','score']]
score1.columns = ['image_id','score1']
score2 = pd.read_csv('../../score/version6_train_score.csv')[['image_name','score']]
score2.columns = ['image_id','score2']
score3 = pd.read_csv('../../score/version7_train_score.csv')[['image_name','score']]
score3.columns = ['image_id','score3']
score4 = pd.read_csv('../../score/version8_train_score.csv')[['image_name','score']]
score4.columns = ['image_id','score4']
score5 = pd.read_csv('../../score/version9_train_score.csv')[['image_name','score']]
score5.columns = ['image_id','score5']
score6 = pd.read_csv('../../score/version10_train_score.csv')[['image_name','score']]
score6.columns = ['image_id','score6']
train = train.merge(score1, on='image_id')
train = train.merge(score2, on='image_id')
train = train.merge(score3, on='image_id')
train = train.merge(score4, on='image_id')
train = train.merge(score5, on='image_id')
train = train.merge(score6, on='image_id')

In [5]:
for idx in range(7):
    idx += 1
    try:
        print('Model:',idx,'AUC:',roc_auc_score(train.target, train['score'+str(idx)]))
    except:
        pass

Model: 1 AUC: 0.7892955637114458
Model: 2 AUC: 0.9157784316069277
Model: 3 AUC: 0.9181271779291388
Model: 4 AUC: 0.9277261736361294
Model: 5 AUC: 0.9152947242991631
Model: 6 AUC: 0.9201749204407612

In [6]:
test = pd.read_csv('../../data/combined/test.csv')
test = test.rename(columns={'image_name':'image_id'})[['image_id']]
score1 = pd.read_csv('../../score/metadata_test_score.csv')[['image_name','target']]
score1.columns = ['image_id','score1']
score2 = pd.read_csv('../../score/version6_test_score.csv')[['image_name','target']]
score2.columns = ['image_id','score2']
score3 = pd.read_csv('../../score/version7_test_score.csv')[['image_name','target']]
score3.columns = ['image_id','score3']
score4 = pd.read_csv('../../score/version8_test_score.csv')[['image_name','target']]
score4.columns = ['image_id','score4']
score5 = pd.read_csv('../../score/version9_test_score.csv')[['image_name','target']]
score5.columns = ['image_id','score5']
score6 = pd.read_csv('../../score/version10_test_score.csv')[['image_name','target']]
score6.columns = ['image_id','score6']
test = test.merge(score1, on='image_id')
test = test.merge(score2, on='image_id')
test = test.merge(score3, on='image_id')
test = test.merge(score4, on='image_id')
test = test.merge(score5, on='image_id')
test = test.merge(score6, on='image_id')

In [7]:
train.head().round(3)

       image_id  fold  target  score1  score2  score3  score4  score5  score6
0  ISIC_2637011     0       0   0.014   0.016   0.096   0.019   0.030   0.004
1  ISIC_0015719     2       0   0.016   0.003   0.001   0.007   0.005   0.001
2  ISIC_0052212     4       0   0.015   0.002   0.005   0.005   0.002   0.000
3  ISIC_0068279     0       0   0.018   0.133   0.044   0.030   0.020   0.010
4  ISIC_0074268     4       0   0.016   0.001   0.000   0.002   0.000   0.000

In [8]:
test.head().round(3)

       image_id  score1  score2  score3  score4  score5  score6
0  ISIC_0052060   0.018   0.024   0.006   0.016   0.005   0.001
1  ISIC_0052349   0.018   0.002   0.006   0.014   0.001   0.002
2  ISIC_0058510   0.016   0.001   0.001   0.007   0.001   0.002
3  ISIC_0073313   0.018   0.003   0.001   0.004   0.000   0.000
4  ISIC_0073502   0.018   0.231   0.061   0.146   0.226   0.114

In [9]:
train.describe().round(2).T

          count  mean   std   min   25%   50%   75%   max
fold    32691.0  2.02  1.42  0.00  1.00  2.00  3.00  4.00
target  32691.0  0.02  0.13  0.00  0.00  0.00  0.00  1.00
score1  32691.0  0.02  0.01  0.01  0.01  0.02  0.02  0.10
score2  32691.0  0.06  0.14  0.00  0.00  0.01  0.04  1.00
score3  32691.0  0.08  0.16  0.00  0.00  0.01  0.07  1.00
score4  32691.0  0.06  0.12  0.00  0.01  0.02  0.05  0.99
score5  32691.0  0.04  0.12  0.00  0.00  0.00  0.02  1.00
score6  32691.0  0.05  0.13  0.00  0.00  0.00  0.03  1.00

In [10]:
test.describe().round(2).T

          count  mean   std   min   25%   50%   75%   max
score1  10982.0  0.02  0.00  0.01  0.02  0.02  0.02  0.08
score2  10982.0  0.08  0.16  0.00  0.00  0.02  0.08  1.00
score3  10982.0  0.11  0.19  0.00  0.00  0.03  0.12  1.00
score4  10982.0  0.08  0.14  0.00  0.01  0.03  0.09  0.99
score5  10982.0  0.06  0.13  0.00  0.00  0.01  0.06  1.00
score6  10982.0  0.07  0.14  0.00  0.00  0.01  0.06  1.00

In [11]:
train[[x for x in FEATURES]].corr().round(4)

        score2  score3  score4  score5  score6
score2  1.0000  0.8032  0.8376  0.6929  0.7041
score3  0.8032  1.0000  0.8310  0.6960  0.7245
score4  0.8376  0.8310  1.0000  0.7230  0.7357
score5  0.6929  0.6960  0.7230  1.0000  0.7150
score6  0.7041  0.7245  0.7357  0.7150  1.0000

In [12]:
test[[x for x in FEATURES]].corr().round(4)

        score2  score3  score4  score5  score6
score2  1.0000  0.8671  0.8987  0.7949  0.7984
score3  0.8671  1.0000  0.8907  0.7965  0.8038
score4  0.8987  0.8907  1.0000  0.8197  0.8126
score5  0.7949  0.7965  0.8197  1.0000  0.8252
score6  0.7984  0.8038  0.8126  0.8252  1.0000

In [13]:
def fitModel(fold):
    scale = QuantileTransformer(n_quantiles=100, output_distribution='normal')
    train_subset = train[train['fold'] != fold].reset_index(drop=True).copy()
    valid_subset = train[train['fold'] == fold].reset_index(drop=True).copy()
    print('Data:', train_subset.shape, valid_subset.shape)
    valid_driver = valid_subset[['image_id','target']].copy()
    test_driver = test[['image_id']].copy()
    X_train, y_train = train_subset[FEATURES], train_subset[TARGET]
    X_valid, y_valid = valid_subset[FEATURES], valid_subset[TARGET]
    X_test = test[FEATURES]
    X_train = scale.fit_transform(X_train)
    X_valid = scale.transform(X_valid)
    X_test = scale.transform(X_test)
    model = LogisticRegression(C=1., fit_intercept=True)
    model.fit(X_train, y_train)
    print('Weights:', model.coef_.round(4))
    valid_driver['score'] = model.predict_proba(X_valid)[:,1]
    test_driver['score'] = model.predict_proba(X_test)[:,1]
    print('Stacked AUC:', round(roc_auc_score(valid_driver.target, valid_driver.score), 4))
    print('Output:', test_driver.shape)
    return valid_driver, test_driver

In [14]:
valid_0, test_0 = fitModel(0)

Data: (26213, 9) (6478, 9)
Weights: [[0.0804 0.4057 0.9852 0.3828 0.6034]]
Stacked AUC: 0.9546
Output: (10982, 2)

In [15]:
valid_1, test_1 = fitModel(1)

Data: (26217, 9) (6474, 9)
Weights: [[0.0378 0.304  1.1692 0.4319 0.6642]]
Stacked AUC: 0.9206
Output: (10982, 2)

In [16]:
valid_2, test_2 = fitModel(2)

Data: (26263, 9) (6428, 9)
Weights: [[0.1598 0.3764 1.0842 0.3678 0.492 ]]
Stacked AUC: 0.9307
Output: (10982, 2)

In [17]:
valid_3, test_3 = fitModel(3)

Data: (26013, 9) (6678, 9)
Weights: [[0.057  0.4287 1.0991 0.3737 0.5368]]
Stacked AUC: 0.943
Output: (10982, 2)

In [18]:
valid_4, test_4 = fitModel(4)

Data: (26058, 9) (6633, 9)
Weights: [[0.2346 0.1604 1.1111 0.2896 0.707 ]]
Stacked AUC: 0.9421
Output: (10982, 2)

In [19]:
valid_data = valid_0.append(valid_1).append(valid_2).append(valid_3).append(valid_4)

In [20]:
test_data = test_0.append(test_1).append(test_2).append(test_3).append(test_4)

In [21]:
valid_data = valid_data.groupby(['image_id','target']).mean().reset_index()
test_data = test_data.groupby('image_id').mean().reset_index()

In [22]:
valid_data.shape, test_data.shape

((32691, 3), (10982, 2))

In [23]:
roc_auc_score(valid_data.target, valid_data.score)

0.9381094248417793

In [24]:
valid_data = valid_data[['image_id','score']]
valid_data.to_csv('../../score/regress_2_train.csv', index=False)

In [25]:
test_data.columns = ['image_name','target']
test_data.to_csv('../../score/regress_2_test.csv', index=False)